# reloadly_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ReloadlySdk
  # RecipientPhoneDetails Model.
  class RecipientPhoneDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :country_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :phone_number

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['country_code'] = 'countryCode'
      @_hash['phone_number'] = 'phoneNumber'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(country_code = nil,
                   phone_number = nil)
      @country_code = country_code
      @phone_number = phone_number
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      country_code = hash.key?('countryCode') ? hash['countryCode'] : nil
      phone_number = hash.key?('phoneNumber') ? hash['phoneNumber'] : nil

      # Create object from extracted values.
      RecipientPhoneDetails.new(country_code,
                                phone_number)
    end
  end
end
