# reloadly_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ReloadlySdk
  # ReloadlyAirtimeFxRatesRequest Model.
  class ReloadlyAirtimeFxRatesRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :operator_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :amount

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['operator_id'] = 'operatorId'
      @_hash['amount'] = 'amount'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(operator_id = nil,
                   amount = nil)
      @operator_id = operator_id
      @amount = amount
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      operator_id = hash.key?('operatorId') ? hash['operatorId'] : nil
      amount = hash.key?('amount') ? hash['amount'] : nil

      # Create object from extracted values.
      ReloadlyAirtimeFxRatesRequest.new(operator_id,
                                        amount)
    end
  end
end
