# reloadly_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ReloadlySdk
  # ReloadlyAuthRequest Model.
  class ReloadlyAuthRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :client_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :client_secret

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :grant_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :audience

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['client_id'] = 'client_id'
      @_hash['client_secret'] = 'client_secret'
      @_hash['grant_type'] = 'grant_type'
      @_hash['audience'] = 'audience'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(client_id = nil,
                   client_secret = nil,
                   grant_type = nil,
                   audience = nil)
      @client_id = client_id
      @client_secret = client_secret
      @grant_type = grant_type
      @audience = audience
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      client_id = hash.key?('client_id') ? hash['client_id'] : nil
      client_secret = hash.key?('client_secret') ? hash['client_secret'] : nil
      grant_type = hash.key?('grant_type') ? hash['grant_type'] : nil
      audience = hash.key?('audience') ? hash['audience'] : nil

      # Create object from extracted values.
      ReloadlyAuthRequest.new(client_id,
                              client_secret,
                              grant_type,
                              audience)
    end
  end
end
