# reloadly_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ReloadlySdk
  # ReloadlyUtilityPaymentsPayBillRequest Model.
  class ReloadlyUtilityPaymentsPayBillRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :subscriber_account_number

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :amount

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :biller_id

    # TODO: Write general description for this method
    # @return [TrueClass|FalseClass]
    attr_accessor :use_local_amount

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['subscriber_account_number'] = 'subscriberAccountNumber'
      @_hash['amount'] = 'amount'
      @_hash['biller_id'] = 'billerId'
      @_hash['use_local_amount'] = 'useLocalAmount'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(subscriber_account_number = nil,
                   amount = nil,
                   biller_id = nil,
                   use_local_amount = nil)
      @subscriber_account_number = subscriber_account_number
      @amount = amount
      @biller_id = biller_id
      @use_local_amount = use_local_amount
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      subscriber_account_number =
        hash.key?('subscriberAccountNumber') ? hash['subscriberAccountNumber'] : nil
      amount = hash.key?('amount') ? hash['amount'] : nil
      biller_id = hash.key?('billerId') ? hash['billerId'] : nil
      use_local_amount =
        hash.key?('useLocalAmount') ? hash['useLocalAmount'] : nil

      # Create object from extracted values.
      ReloadlyUtilityPaymentsPayBillRequest.new(subscriber_account_number,
                                                amount,
                                                biller_id,
                                                use_local_amount)
    end
  end
end
