# reloadly_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ReloadlySdk
  # ReloadlyNumberLookupPostRequest Model.
  class ReloadlyNumberLookupPostRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :number

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :country_code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['number'] = 'number'
      @_hash['country_code'] = 'countryCode'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(number = nil,
                   country_code = nil)
      @number = number
      @country_code = country_code
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      number = hash.key?('number') ? hash['number'] : nil
      country_code = hash.key?('countryCode') ? hash['countryCode'] : nil

      # Create object from extracted values.
      ReloadlyNumberLookupPostRequest.new(number,
                                          country_code)
    end
  end
end
