# reloadly_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ReloadlySdk
  # ReloadlyGiftCardsOrdersRequest Model.
  class ReloadlyGiftCardsOrdersRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :product_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :country_code

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :quantity

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :unit_price

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :custom_identifier

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :sender_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :recipient_email

    # TODO: Write general description for this method
    # @return [RecipientPhoneDetails]
    attr_accessor :recipient_phone_details

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['product_id'] = 'productId'
      @_hash['country_code'] = 'countryCode'
      @_hash['quantity'] = 'quantity'
      @_hash['unit_price'] = 'unitPrice'
      @_hash['custom_identifier'] = 'customIdentifier'
      @_hash['sender_name'] = 'senderName'
      @_hash['recipient_email'] = 'recipientEmail'
      @_hash['recipient_phone_details'] = 'recipientPhoneDetails'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(product_id = nil,
                   country_code = nil,
                   quantity = nil,
                   unit_price = nil,
                   custom_identifier = nil,
                   sender_name = nil,
                   recipient_email = nil,
                   recipient_phone_details = nil)
      @product_id = product_id
      @country_code = country_code
      @quantity = quantity
      @unit_price = unit_price
      @custom_identifier = custom_identifier
      @sender_name = sender_name
      @recipient_email = recipient_email
      @recipient_phone_details = recipient_phone_details
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      product_id = hash.key?('productId') ? hash['productId'] : nil
      country_code = hash.key?('countryCode') ? hash['countryCode'] : nil
      quantity = hash.key?('quantity') ? hash['quantity'] : nil
      unit_price = hash.key?('unitPrice') ? hash['unitPrice'] : nil
      custom_identifier =
        hash.key?('customIdentifier') ? hash['customIdentifier'] : nil
      sender_name = hash.key?('senderName') ? hash['senderName'] : nil
      recipient_email =
        hash.key?('recipientEmail') ? hash['recipientEmail'] : nil
      recipient_phone_details = RecipientPhoneDetails.from_hash(hash['recipientPhoneDetails']) if
        hash['recipientPhoneDetails']

      # Create object from extracted values.
      ReloadlyGiftCardsOrdersRequest.new(product_id,
                                         country_code,
                                         quantity,
                                         unit_price,
                                         custom_identifier,
                                         sender_name,
                                         recipient_email,
                                         recipient_phone_details)
    end
  end
end
