# reloadly_sdk
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ReloadlySdk
  # SenderPhone Model.
  class SenderPhone < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :country_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :number

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['country_code'] = 'countryCode'
      @_hash['number'] = 'number'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(country_code = nil,
                   number = nil)
      @country_code = country_code
      @number = number
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      country_code = hash.key?('countryCode') ? hash['countryCode'] : nil
      number = hash.key?('number') ? hash['number'] : nil

      # Create object from extracted values.
      SenderPhone.new(country_code,
                      number)
    end
  end
end
